// Code generated by "stringer -type=Channel"; DO NOT EDIT

package channels

import "fmt"

const _Channel_name = "stablebetaalpha"

var _Channel_index = [...]uint8{0, 6, 10, 15}

func (i Channel) String() string {
	i -= 1
	if i < 0 || i >= Channel(len(_Channel_index)-1) {
		return fmt.Sprintf("Channel(%d)", i+1)
	}
	return _Channel_name[_Channel_index[i]:_Channel_index[i+1]]
}
